spring:
  jpa:
    hibernate:
      ddl-auto: update

# Datasource
spring.datasource:
  url: jdbc:h2:file:~/test
  username: sa
  password:
  driver-class-name: "org.h2.Driver"

javafx:
    title: Teco
    stage:
        resizable: true